        Console.WriteLine("NFC West       W   L  T");
        Console.WriteLine("-----------------------");
        Console.WriteLine("Seattle        13  3  0");
        Console.WriteLine("San Francisco  12  4  0");
        Console.WriteLine("Arizona        10  6  0");
        Console.WriteLine("St. Louis      7   9  0");
        Console.WriteLine("");
        Console.WriteLine("NFC North      W   L  T");
        Console.WriteLine("-----------------------");
        Console.WriteLine("Green Bay      8   7  1");
        Console.WriteLine("Chicago        8   8  0");
        Console.WriteLine("Detroit        7   9  0");
        Console.WriteLine("Minnesota      5  10  1");